# Site settings
title: My Blog
email: 254586414@qq.com
description: > # this means to ignore newlines until "baseurl:"
 You'll Never Walk Alone  
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://Hejuntian.github.io
github_username:  Hejuntian
github_repo: https://github.com/Hejuntian/Hejuntian.github.io
tableau_public: https://public.tableau.com/profile/.4824#!/
Myfirstwork_web: https://Hejuntian.github.io/Myfirstwork/

# Build settings
markdown: kramdown